### ISSUE TITLE
Suggestion & Bug: Textures

### ISSUE THREAD

**Issue by IdrisQe** [CrimsonDawn45/survival-additions#2]
Since the theme of the mod is based around crude tools, it would be nice if all the tools added had crude textures. The Flint, Bone, and Teracotta stuff is good, but the Sandstone, Netherrack, and other such tools just have Vanilla tool recolors, which doesn't seem to fit given the appearance of build quality the tools have.

Additionally, as shown in the included pictures, the Flint tool textures seem to have some visual artifacts. I haven't noticed them ingame yet and i'm not entirely sure they even show up ingame, but I still feel the need to point it out.
![image](https://user-images.githubusercontent.com/40530630/45911651-1699f780-bdcb-11e8-90ea-4f63e92da1e7.png)
![image](https://user-images.githubusercontent.com/40530630/45911653-21548c80-bdcb-11e8-91d9-c3e05676b359.png)
![image](https://user-images.githubusercontent.com/40530630/45911659-33362f80-bdcb-11e8-856e-b18aa2502f39.png)
![image](https://user-images.githubusercontent.com/40530630/45911666-4517d280-bdcb-11e8-8603-ec8812f6b5e8.png)
![image](https://user-images.githubusercontent.com/40530630/45911678-64166480-bdcb-11e8-98fb-3a37f1bc5fbe.png)

**Comment by StellarWind22** [comment]
Yeah idk I thought I removed those artifacts last update also I’ve been working on making better textures for the other tools but idk I just cant seem to get the other ones to look right

Sent from Mail for Windows 10

From: IdrisQe
Sent: Friday, September 21, 2018 6:23 PM
To: CrimsonDawn45/survival-additions
Cc: Subscribed
Subject: [CrimsonDawn45/survival-additions] Suggestion & Bug: Textures (#2)

Since the theme of the mod is based around crude tools, it would be nice if all the tools added had crude textures. The Flint, Bone, and Teracotta stuff is good, but the Sandstone, Netherrack, and other such tools just have Vanilla tool recolors, which doesn't seem to fit given the appearance of build quality the tools have.
Additionally, as shown in the included pictures, the Flint tool textures seem to have some visual artifacts. I haven't noticed them ingame yet and i'm not entirely sure they even show up ingame, but I still feel the need to point it out.
